name = "josiahjophlin"
type = "webpack"
account_id = "d1402bd793481efb951022c2bddb2a51"
workers_dev = true

[env.production]
zone_id = "e6f842264de6ce590273ecd686cce781"
route = "*josiahjophlin.dev/*"

[site]
bucket = "./__sapper__/export"
entry-point = "workers-site"
