name: Build, Test and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Check out code, configure this env for node, & install dependencies
      - name: Checkout Code
        uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm install

      # Run the build-script to create a Sapper export folder.
      - name: Build
        run: npm run export
        env:
          CI: true # Prevent output being too verbose.

      # Use Github's upload-artifact action to upload build
      # We only want the `export` folder here which contains our (optimised) static site.
      - name: Save Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: site-artifact # A unique key (and name) for the artifact in question.
          path: __sapper__/export # This is what we'd like to keep

  # Deploy to our production Cloudflare worker-site
  deploy-production:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest

    # This task *only* runs on the master branch.
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # We download the website artifact to deploy this time
      - name: Download Website Artifact
        uses: actions/download-artifact@v1
        with:
          name: site-artifact
          path: __sapper__/export

      # Publish to Cloudflare with wrangler
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
